# Generated by Django 4.0.3 on 2022-04-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('comp', 'Kompyuter'), ('lang', 'Ingliz tili')], default='comp', max_length=10, verbose_name='Kurs turi')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image_url', models.URLField(verbose_name='Kurs rasmi (online)')),
                ('content', models.TextField(verbose_name="Kurs haqida ma'lumot")),
                ('faq', models.TextField(verbose_name="Ko'p beriladigan savollar")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='main.category', verbose_name="Kurs yo'nalishi")),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="O'qituvchi")),
                ('image_url', models.URLField(verbose_name="O'qituchi rasmi (online)")),
                ('content', models.TextField(verbose_name="O'qituchi haqida ma'lumot")),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='main.course', verbose_name='Kurs nomi')),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
    ]
