# Generated by Django 4.0.3 on 2022-04-22 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Yo'nalish nomi")),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('comp', 'Kompyuter'), ('lang', 'Ingliz tili')], default='comp', max_length=10, verbose_name='Kurs turi')),
            ],
            options={
                'verbose_name': "Yo'nalish ",
                'verbose_name_plural': "Yo'nalishlar",
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image_url', models.URLField(verbose_name='Kurs rasmi (online)')),
                ('price', models.PositiveIntegerField(default=0, verbose_name="Kurs narxi (so'm)")),
                ('content', models.TextField(max_length=1020, null=True, verbose_name="Kurs haqida ma'lumot")),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='main.category', verbose_name="Kurs yo'nalishi")),
            ],
            options={
                'verbose_name': 'Kurs ',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Foydalanuvchi')),
                ('username', models.CharField(max_length=100, null=True, verbose_name='Telegram username')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='Telefon')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi ',
                'verbose_name_plural': 'Foydalanivchilar',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="O'qituvchi")),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('image_url', models.URLField(verbose_name="O'qituchi rasmi (online)")),
                ('content', models.TextField(max_length=1020, verbose_name="O'qituchi haqida ma'lumot")),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='main.course', verbose_name='Kurs nomi')),
            ],
            options={
                'verbose_name': "O'qituvchi ",
                'verbose_name_plural': "O'qituvchilar",
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Oylik reja')),
                ('content', models.TextField(max_length=4090, verbose_name="Mavzular ro'yhati")),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mavzular', to='main.course', verbose_name='Mavzular')),
            ],
            options={
                'verbose_name': 'Mavzu ',
                'verbose_name_plural': 'Mavzular',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Savol')),
                ('answer', models.TextField(max_length=4000, verbose_name='Javob')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='main.course', verbose_name='Mavzular')),
            ],
            options={
                'verbose_name': 'Savol - javob ',
                'verbose_name_plural': 'Savollar',
            },
        ),
    ]
