# Generated by Django 4.0.1 on 2022-04-06 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_options_course_subject_teacher_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='Savol')),
                ('answer', models.CharField(max_length=200, verbose_name='Javob')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Oylik reja')),
                ('content', models.TextField(verbose_name="Mavzular ro'yhati")),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faqs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.faq', verbose_name="Ko'p beriladigan savollar"),
        ),
        migrations.AddField(
            model_name='course',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.subject', verbose_name="Mavzular ro'yhati"),
        ),
    ]
