# Generated by Django 4.0.1 on 2022-04-06 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_faq_subject_course_faqs_course_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faqs',
        ),
        migrations.RemoveField(
            model_name='course',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mavzular', to='main.course', verbose_name='Mavzular'),
        ),
    ]
