# Generated by Django 4.0.1 on 2022-04-06 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_course_faqs_remove_course_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='savollar', to='main.course', verbose_name='Mavzular'),
        ),
    ]
