# Generated by Django 4.0.3 on 2022-04-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_faq_options_alter_subject_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faq',
        ),
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.TextField(null=True, verbose_name="Kurs haqida ma'lumot"),
        ),
    ]
