# Generated by Django 4.0.3 on 2022-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_course_faq_course_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name="Kurs narxi (so'm)"),
        ),
    ]
