# Generated by Django 4.0.3 on 2022-04-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Qo'shilgan vaqt"),
        ),
    ]
