# Generated by Django 4.0.3 on 2022-04-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_user_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create',
        ),
    ]
