# Generated by Django 4.0.3 on 2022-04-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_user_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': "Yo'nalish ", 'verbose_name_plural': "Yo'nalishlar"},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Kurs ', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'Savol - javob ', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Mavzu ', 'verbose_name_plural': 'Mavzular'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': "O'qituvchi ", 'verbose_name_plural': "O'qituvchilar"},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi ', 'verbose_name_plural': 'Foydalanivchilar'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course',
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(related_name='teachers', to='main.course', verbose_name='Kurs nomi'),
        ),
    ]
