# Generated by Django 4.0.3 on 2022-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_teacher_course_teacher_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(max_length=1020, null=True, verbose_name="Kurs haqida ma'lumot"),
        ),
        migrations.AlterField(
            model_name='subject',
            name='content',
            field=models.TextField(max_length=4090, verbose_name="Mavzular ro'yhati"),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='content',
            field=models.TextField(max_length=1020, verbose_name="O'qituchi haqida ma'lumot"),
        ),
    ]
